wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720775706
    t:
      1:
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.10.14
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
    framework: sklearn
