wandb_version: 1

betas:
  value:
  - 0.7
  - 0.9
clamp_mode:
  value: softplus
dataset:
  value: lock
discriminator:
  value: ProgressiveEncoderDiscriminator
fade_steps:
  value: 5000
fov:
  value: 55.711350719633145
generator:
  value: ImplicitGenerator3d
grad_clip:
  value: 9.374413144922771
h_mean:
  value: 0
h_stddev:
  value: 1.0471975511965976
hierarchical_sample:
  value: true
latent_dim:
  value: 512
learnable_dist:
  value: true
model:
  value: TALLSIREN
r1_lambda:
  value: 2.8274794789105417
ray_end:
  value: 1.3
ray_start:
  value: 0.7
sample_dist:
  value: lock
topk_interval:
  value: 1000
topk_v:
  value: 0.371480772643457
unique_lr:
  value: false
v_mean:
  value: 0.7417649320975901
v_stddev:
  value: 0.7417649320975901
weight_decay:
  value: 0.06708967208799631
white_back:
  value: true
z_dist:
  value: gaussian
z_lambda:
  value: 0
